# Created with WinGet Updater using komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Instruqt.CLI
PackageVersion: 2286-9c72cac
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: instruqt.exe
InstallModes:
- silent
UpgradeBehavior: install
ReleaseDate: 2025-07-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/instruqt/cli/releases/download/2286-9c72cac/instruqt-windows.zip
  InstallerSha256: 5AE65DFC574DB86AFF18653C2D4591CD214D7733B6608EC6AE23A328082C7ECC
ManifestType: installer
ManifestVersion: 1.6.0
